Handle the situation of a NoClassDefFoundError during class loading. Let the NoClassDefFoundError class loader error fall through so that BeanShell can continue with it's loading efforts.  If the class cannot be loaded than an EvalError will eventually be thrown.